### ISSUE TITLE
Villager GUI bug

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#302] opened 2023-03-04 01:02 UTC
When double clicking an item while in the villager trade GUI, the xp bar and levels reset. However after re-entering the trade, it pulls the correct data back likely because this is a client-side bug.

**Comment by ammoore00** [comment] 2023-03-04 01:31
Duplicate of https://github.com/BTW-Community/BTW-Public/issues/291

Also, not a useful title.

**Closed by ammoore00** 2023-03-04 01:31 UTC
