### ISSUE TITLE
Allow wolves to become hostile by attacking them, even when dealing no damage

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#185] opened 2022-03-01 22:06 UTC
Sometimes, you're famished.  Starving even!  And during those times, wouldn't you like to go for a nice tall glass of suicide?

**Comment by ammoore00** [comment] 2022-03-04 17:18
Similar enough to be counter as a duplicate of #184

**Closed by ammoore00** 2022-03-04 17:18 UTC
Labels: duplicate
