### ISSUE TITLE
Particles to indicate a valid fishing area

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#282] opened 2023-01-13 00:38 UTC
Commander Frost suggested: add subtle particles around the fishing hook to show if you can catch fish there or not.
This is a small quality of life feature to help the player pick a valid depth for fishing instead of wasting time.

**Comment by ammoore00** [comment] 2023-01-13 02:32
Right, i meant to make this and then forgot, thank you :)

**Comment by PlasmaFox256** [comment] 2023-01-30 06:15
Pushed branch into CE2.0.2

**Comment by ammoore00** [comment] 2023-01-30 07:33
Reopening as the code has not been merged. Yes there is an open PR with this but I haven't had time to evaluate it yet, and so closing the issue is not appropriate until the code is merged into main.

**Comment by ammoore00** [comment] 2023-02-05 07:08
Completed for 2.0.2

**Closed by ammoore00** 2023-02-05 07:08 UTC
Labels: addition
