### ISSUE TITLE
Oven Insides Cosmetic Glitch

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#180] opened 2022-02-20 02:02 UTC
Seems to happen when I quit out of the game and get back on.  Items still appear visible inside, so I don't see it really hurting the gameplay in any way.  Seems to go away on surrounding block update.

Single Player
BTW-CE-1.3.6-client
BetterTerrainAddon-2.0.6-client
Quieter MillStone-client

![Oven Cavity Cosmetic Glitch](https://user-images.githubusercontent.com/77890127/154825489-d9e31797-43f0-4ea1-8dd2-77dab4020a43.gif)

**Comment by ammoore00** [comment] 2022-02-25 23:01
Yeah, known issue. No idea what the cause is, but it is something on my radar.

**Comment by Hirachosan** [comment] 2022-07-01 20:37
traced this bug to `RenderBlocks.renderStandardBlockWithColorMultiplier(Block block, int x, int y, int z, float red, float green, float blue)`
only hamper basket and oven are using this method, through `FCModelBlock.RenderAsBlockWithColorMultiplier()`

not entirely sure what's causing the issues in there though, as its really confusing to read =/

**Comment by Hirachosan** [comment] 2022-07-01 20:42
Looking back at that method in BTW b000003 it looks completely different, I suppose things got changed here for MCPatcher and it is messing around. It seems there's a lot of variables doing nothing and overwriting itself without actually doing stuff

**Comment by Hirachosan** [comment] 2022-07-01 20:53
traced it further to `setColorOpaque_F(RenderBlocksUtils.getColorMultiplierRed(0), RenderBlocksUtils.getColorMultiplierGreen(0), RenderBlocksUtils.getColorMultiplierBlue(0))` on line 6196 RenderBlocks and several using the same method. replacing this part with the pre MCPatcher stuff fixes things. not sure if that's wanted because not sure what the MCPatcher stuff (im assuming) is adding here

**Comment by Hirachosan** [comment] 2022-07-01 20:56
[renderblocksColormultiplier.txt](https://github.com/BTW-Community/BTW-Public/files/9031564/renderblocksColormultiplier.txt)
added old method for reference

**Comment by Hirachosan** [comment] 2022-08-14 22:45
should I just create a PR reverting to the old render code for this particular case?

**Comment by ammoore00** [comment] 2022-08-15 19:27
Fixed for next release

**Comment by ammoore00** [comment] 2022-09-14 20:41
Reponening this because the bug is still happening

**Comment by Hirachosan** [comment] 2022-09-16 16:09
I checked into this a bit again. in  setupColormultiplier, to actually set the colormultipliers up, it asks `	if (!isAmbientOcclusionEnabled() || BlockAPI.getBlockLightValue(block) != 0)

I suspected that this is done so gloom blocks dont apply a colormultiplier. changing this to `	if (!isAmbientOcclusionEnabled() || BlockAPI.getBlockLightValue(block) >= 0)` makes the bug go away. Solution is either this, or check how the block correctly knows its light value?

**Comment by Hirachosan** [comment] 2022-09-16 16:12
plot twist. changing this removes the visual part of the lighting bug!

**Comment by Hirachosan** [comment] 2022-09-16 19:11
yeah I see what you mean now, `BlockAPI.getBlockLightValue(block) != 0 ` basically means if the block is a lightsource, and it then always makes it fully bright

**Comment by Hirachosan** [comment] 2022-09-17 09:36
So the fix that was added last patch didn't work because `RenderBlocks.renderStandardBlockWithColorMultiplier()` is adapted to use only `nonAOMultipliers[][]`. and the added `RenderBlocksUtils.setupColorMultiplier()` only sets up `nonAOMultipliers[][]` if `(!isAmbientOcclusionEnabled() || BlockAPI.getBlockLightValue(block) != 0)`. This is why all the ovens and baskets light up if an oven is lit: it has a light source and starts acting as nonAO. 

I think the intent was to have the insides of ovens not use AO and grab a single colormultiplier based on the light level of the block in front of it seeing as how OvenBlock grabs that multiplier and activates it during this render part

A solution would be to use `RenderBlocks.renderStandardBlock()` instead, but that will give OA inside, which looks kind of off but is hardly noticable

another solution would be to add a method to set up the nonAOmultipliers manually for blocks that arent lightsource while using AO. this could be useful in general

**Comment by Hirachosan** [comment] 2022-10-01 12:23
fixed for next release

**Closed by Hirachosan** 2022-10-01 12:23 UTC
Labels: bug, investigation needed, rendering
